/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 28-ноя-2024 14:44:09 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */



/* Drop Tables */

DROP TABLE IF EXISTS school CASCADE
;

/* Create Tables */

CREATE TABLE school
(
	id bigserial NOT NULL,
	name varchar(100) NULL,
	address varchar(200) NULL,
	created_at timestamp without time zone NULL,
	updated_at timestamp without time zone NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE school ADD CONSTRAINT "PK_school"
	PRIMARY KEY (id)
;

/* Create Table Comments, Sequences for Autonumber Columns */


