/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 13-дек-2024 10:06:28 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS notification_status CASCADE
;

/* Create Tables */

CREATE TABLE notification_status
(
	id bigint NOT NULL,
	notification_type varchar(50) NOT NULL,
	subscirer_id bigint NOT NULL,
	status varchar(20) NOT NULL,
	create_at timestamp without time zone NOT NULL,
	update_at timestamp without time zone NOT NULL,
	attemps bigint NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE notification_status ADD CONSTRAINT "PK_notification_status"
	PRIMARY KEY (id)
;
