/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 28-ноя-2024 14:44:09 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

 

/* Drop Tables */

DROP TABLE IF EXISTS school CASCADE
;

/* Create Tables */

CREATE TABLE school
(
	id bigserial NOT NULL,
	name varchar(100) NULL,
	address varchar(200) NULL,
	created_at timestamp without time zone NULL,
	updated_at timestamp without time zone NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE school ADD CONSTRAINT "PK_school"
	PRIMARY KEY (id)
;

/* Create Table Comments, Sequences for Autonumber Columns */

 
INSERT INTO school (name, address, created_at, updated_at) VALUES
('СОШ №1', 'ул. Ленина, 15', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Гимназия №2', 'пр. Мира, 28', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Лицей №3', 'ул. Пушкина, 42', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('СОШ №4', 'ул. Гагарина, 7', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Гимназия №5', 'ул. Космонавтов, 33', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('СОШ №6', 'ул. Советская, 12', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Лицей №7', 'пр. Победы, 55', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('СОШ №8', 'ул. Маяковского, 18', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Гимназия №9', 'ул. Чехова, 23', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('СОШ №10', 'ул. Толстого, 44', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Лицей №11', 'пр. Ломоносова, 61', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('СОШ №12', 'ул. Достоевского, 37', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Гимназия №13', 'ул. Некрасова, 52', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('СОШ №14', 'пр. Менделеева, 29', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Лицей №15', 'ул. Горького, 81', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('СОШ №16', 'ул. Тютчева, 19', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Гимназия №17', 'пр. Циолковского, 66', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('СОШ №18', 'ул. Фета, 13', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Лицей №19', 'ул. Королёва, 72', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('СОШ №20', 'ул. Тургенева, 88', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Гимназия №21', 'ул. Есенина, 45', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('СОШ №22', 'пр. Жуковского, 31', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Лицей №23', 'ул. Блока, 54', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('СОШ №24', 'ул. Цветаевой, 27', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Гимназия №25', 'пр. Пастернака, 63', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('СОШ №26', 'ул. Ахматовой, 91', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Лицей №27', 'ул. Бродского, 38', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('СОШ №28', 'пр. Мандельштама, 75', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Гимназия №29', 'ул. Окуджавы, 22', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('СОШ №30', 'ул. Высоцкого, 49', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);